user:
  max_length_name: 50
  max_length_email: 250
  min_length_password: 6
  max_length_username: 50
  min_length_username: 4
  previews_per_page: 9
  email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  username_regex: !ruby/regexp '/[A-Za-z0-9\-\_\+]+/'
  name_regex: !ruby/regexp '/\w+/'
  phone_regex: !ruby/regexp '/\A(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\z/'
  website_regex: !ruby/regexp '/https?:\/\/[\S]+/'
  default_avt: "default.jpg"
  verified_image: "verified.png"
  valid_image_types: ["image/jpeg", "image/gif", "image/png"]
  gender_male: 1
  gender_female: 0
  gender_other: 2
  per_of_page: 10
  public_mode: 0
  private_mode: 1
  public_mode_text: "public_mode"
  private_mode_text: "private_mode"
  password_default: "123456"
  role_user: 0
  role_admin: 1
  word_count: 10
  username_specifier: 8
  user_id1: 1
  user_id2: 2
favicon_image: "favicon.png"
disable_link: "javascript:void(0)"
post:
  max_picture_size: 5
  content_type: ["image/jpeg", "image/gif", "image/png"]
  previews_per_page: 4
favicon_image: "favicon.png"
hashtag:
  max_length: 500
favicon_image: "favicon.png"
image_format: "image/jpeg,image/gif,image/png"
bookmark_like:
  like: 0
  bookmark: 1
feed_items_per_page: 3
single_image_size: 1
top_comments: 2
search:
  char_sharp: "#"
  char_at: "@"
notification:
  follow: 0
  like: 1
  comment: 2
  reply: 3
  like_comment: 4
  mention: 5
  request: 6
  accept: 7
  update: "update"
  delete: "delete"
  read: 1
  unread: 0
  type_follow: "follow"
  type_like: "like"
  type_comment: "comment"
  type_reply: "reply"
  type_request: "request"
  type_accept: "accept"
  type_like_comment: "like_comment"
  type_mention: "mention"
  read_s: "read"
relationship:
  accept: 0
  un_accept: 1
host: localhost:3000
facebook_auth_path: "/auth/facebook"
sort_post:
  created_at: 0
  updated_at: 1
  description: 2
  type: "sort"
sort_user:
  created_at: 0
  updated_at: 1
  name: 2
  username: 3
  type: "sort"
search:
  type: "search"
  char_sharp: "#"
  char_at: "@"
facebook_auth_path: "/users/auth/facebook"
default_password: "123456"
factories:
  user:
    phone_number: 0984255640
