user:
  max_length_name: 50
  max_length_email: 250
  min_length_password: 6
  max_length_username: 50
  min_length_username: 4
  email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  username_regex: !ruby/regexp '/\A[a-zA-Z0-9]+\z/'
  default_avt: "default.jpg"
favicon_image: "favicon.png"
